### ISSUE TITLE
Perception objects levitate away

### ISSUE THREAD

**Issue by croomjm** [udacity/robotics-nanodegree-issues#113]
Due to lack of friction and low mass, some of the objects in both the perception exercise 3 and project (especially the create) slowly glide away from initial state even with no applied force. Objects should be updated with appropriate friction/mass. Objects in perception exercise 3 could be fixed in space since they don't need to be grabbed.

**Comment by kylesf** [comment]
@hvpandya Thoughts on this?

**Comment by hvpandya** [comment]
The create does not glide because of lack of friction, it has a motion controller embedded in it since its motion is intentional (consider it an easter egg). 

I do agree that at some point we should update all models with realistic mass, friction and damping properties but that is not something we will pursue in the near future. @kylesf Feel free to keep this ticket in the backlog.
