### ISSUE TITLE
Not enough rote exercises in the classroom

### ISSUE THREAD

**Issue by ezra-schroeder** [udacity/robotics-nanodegree-issues#167]
We received an email in which it was suggested that we add things that Udacity can do to improve this Nanodegree here on Waffle. I would really encourage you to include many, many more (perhaps optional) rote coding exercises. Preferably ones that are *autograded* and possibly where no solution is provided. I believe that many people would be greatly aided by this, and that it is something that would separate Udacity from (for instance) academia & other platforms, and it is something that Udacity is ideally suited for. And I think it is right in line with Sebastian Thrun's vision. People need tons and tons of practice to acquire expertise. You could dramatically streamline people's learning curve by providing dramatically more of this IMHO. For me, I'm trying to find coding exercises on other sites that are applicable. But I lose a lot of time searching for information. Yes, that is a skill that developers, including roboticists of all stripes, need. But, you could nevertheless streamline people's process by reducing that time-overhead by including drastically more exercises. Put the exercises in the classroom and make them autograded but do not include the answer. Better yet *gamify* the Nanodegree by having a leader board & a points system for completing exercises (but make them completely optional). Cheers!

**Comment by sahiljuneja** [comment]
Thanks for the feedback! Is this specific to any content till now? Or you feel this is applicable or a drawback to most/all coding exercises? 

So for example, the Perception content. Most of the exercises build towards the project and/or help understand the concept at hand. Are you stating you would like more exercises that repeat the concepts instead of 1 or 2 of those exercises/quizzes?
