### ISSUE TITLE
Error in Solution

### ISSUE THREAD

**Issue by Chambana** [udacity/robotics-nanodegree-issues#5]
I dont think the solution is right for the color thresholding exercise.  When you put values of 0,0,0, it doesn't provide a totally white image as described.  That is because the bitwise AND operation in the thresholding statement uses < and not <=.  Just change those 3 less than's to less-than-or-equal-to and it'll work fine.  The reason is that some pixels in the original image are totally black (e.g. 0,0,0) and the threshold level (0,0,0) therefore isn't strictly less than this and will reject the mask for that pixel.

**Comment by ryan-keenan** [comment]
Thanks for pointing this out!  There was definitely an inconsistency in the code comments surrounding the function definition.  I actually intended it to use > instead of >= just because when the image is all 1's it actually renders as all black rather than all white (putting it on a 0 to 255) , which was confusing to some people.  I've cleared up the code comments now.
